language: python:2.7
sudo: true

install:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt

script:
    - python -m unittest test.test_apis

after_success:
    - echo "PASSED ALL UNIT TEST"

after_failure:
    - echo "UNIT TEST FAILURE"
